from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[1]
THIS_FILE = Path(__file__).resolve()
SCANNED_EXTENSIONS = {".py", ".md"}
BANNED_CREDIT_TOKENS = (
    "claude",
    "chatgpt",
    "anthropic",
    "openai",
    "copilot",
    "codex",
    "generated by ai",
    "ai-assisted",
)
MOJIBAKE_MARKERS = (
    "â†",
    "â–",
    "Ã©",
    "Â·",
    "ðŸ",
)
EXCLUDED_DIR_NAMES = {
    ".git",
    ".venv",
    "build",
    "dist",
    "__pycache__",
    ".pytest_cache",
}


def _iter_scanned_files() -> list[Path]:
    files: list[Path] = []
    for path in REPO_ROOT.rglob("*"):
        if not path.is_file():
            continue
        if path.resolve() == THIS_FILE:
            continue
        if path.suffix.lower() not in SCANNED_EXTENSIONS:
            continue
        if any(part in EXCLUDED_DIR_NAMES for part in path.parts):
            continue
        files.append(path)
    return files


def test_no_ai_credit_tokens_in_source_or_docs() -> None:
    offenders: list[str] = []
    for path in _iter_scanned_files():
        text = path.read_text(encoding="utf-8")
        lowered = text.lower()
        for token in BANNED_CREDIT_TOKENS:
            if token in lowered:
                rel = path.relative_to(REPO_ROOT)
                offenders.append(f"{rel}: {token}")
    assert not offenders, "Found banned credit token(s):\n" + "\n".join(offenders)


def test_no_common_mojibake_markers() -> None:
    offenders: list[str] = []
    for path in _iter_scanned_files():
        text = path.read_text(encoding="utf-8")
        for marker in MOJIBAKE_MARKERS:
            if marker in text:
                rel = path.relative_to(REPO_ROOT)
                offenders.append(f"{rel}: {marker}")
    assert not offenders, "Found mojibake marker(s):\n" + "\n".join(offenders)
