"""Static constants: known plugins, stage list, UI colors."""
from src.models.plugin import KnownPluginInfo

# Known Skyline plugins with descriptions
KNOWN_PLUGINS = {
    "libarcropolis.nro": KnownPluginInfo(
        filename="libarcropolis.nro",
        display_name="ARCropolis",
        description="Core mod loader for SSBU. Enables file replacement mods. Required for most mods to work.",
        url="https://github.com/Raytwo/ARCropolis",
        required=True,
    ),
    "libparam_hook.nro": KnownPluginInfo(
        filename="libparam_hook.nro",
        display_name="Param Hook",
        description="Hooks parameter file loading for dynamic param modification at runtime.",
    ),
    "libacmd_hook.nro": KnownPluginInfo(
        filename="libacmd_hook.nro",
        display_name="ACMD Hook",
        description="Hooks the Animation Command (ACMD) system for custom movesets and attacks.",
    ),
    "libnro_hook.nro": KnownPluginInfo(
        filename="libnro_hook.nro",
        display_name="NRO Hook",
        description="Enables loading additional NRO plugins at runtime.",
    ),
    "libtraining_modpack.nro": KnownPluginInfo(
        filename="libtraining_modpack.nro",
        display_name="Training Modpack",
        description="Enhanced training mode with frame data, input display, and advanced options.",
        url="https://github.com/jugeeya/UltimateTrainingModpack",
    ),
    "libskyline_web.nro": KnownPluginInfo(
        filename="libskyline_web.nro",
        display_name="Skyline Web",
        description="Web-based plugin manager accessible from the console's browser.",
    ),
    "libhdr.nro": KnownPluginInfo(
        filename="libhdr.nro",
        display_name="HDR (HewDraw Remix)",
        description="Major gameplay overhaul mod with rebalanced fighters and mechanics.",
        url="https://github.com/HDR-Development/HewDraw-Remix",
    ),
    "libsmashline_plugin.nro": KnownPluginInfo(
        filename="libsmashline_plugin.nro",
        display_name="Smashline",
        description="Framework for custom fighter movesets. Enables ACMD script replacement and status script changes.",
    ),
    "libparam_config.nro": KnownPluginInfo(
        filename="libparam_config.nro",
        display_name="Param Config",
        description="Allows per-mod parameter file configuration. Required by many moveset mods for custom fighter params.",
    ),
    "libstage_config.nro": KnownPluginInfo(
        filename="libstage_config.nro",
        display_name="Stage Config",
        description="Stage-specific configuration plugin. Enables custom stage parameters and modded stage setups.",
    ),
    "libcss_preserve.nro": KnownPluginInfo(
        filename="libcss_preserve.nro",
        display_name="CSS Preserve",
        description="Preserves Character Select Screen cursor positions and selections between matches.",
    ),
    "liblatency_slider_de.nro": KnownPluginInfo(
        filename="liblatency_slider_de.nro",
        display_name="Latency Slider",
        description="Adds a latency/input delay slider for fine-tuning online play responsiveness.",
    ),
    "libone_slot_eff.nro": KnownPluginInfo(
        filename="libone_slot_eff.nro",
        display_name="One Slot Effect",
        description="Allows visual effects to be loaded per costume slot. Enables unique effects for each alt costume.",
        stable_mode_keep=True,
    ),
    "libresults_screen.nro": KnownPluginInfo(
        filename="libresults_screen.nro",
        display_name="Results Screen",
        description="Customizes the results/victory screen. Shows correct character names and portraits for custom fighters.",
    ),
    "libthe_csk_collection.nro": KnownPluginInfo(
        filename="libthe_csk_collection.nro",
        display_name="The CSK Collection",
        description="Collection of game tweaks and quality-of-life improvements for competitive and casual play.",
    ),
    "libtesting.nro": KnownPluginInfo(
        filename="libtesting.nro",
        display_name="Testing Plugin",
        description="Development/testing plugin for debugging and testing mod functionality.",
    ),
}

# SSBU vanilla stages used by the music page (stage_id -> display name).
#
# `ui_stage_id_menu` remains an app-owned pseudo stage for the built-in main
# menu slot. The rest are the actual in-game stage IDs used by SSBU.
VANILLA_STAGES = {
    "ui_stage_id_menu": "Main Menu",
    "ui_stage_battle_field": "Battlefield",
    "ui_stage_battle_field_l": "Big Battlefield",
    "ui_stage_end": "Final Destination",
    "ui_stage_mario_castle64": "Peach's Castle",
    "ui_stage_dk_jungle": "Kongo Jungle",
    "ui_stage_zelda_hyrule": "Hyrule Castle",
    "ui_stage_yoshi_story": "Super Happy Tree",
    "ui_stage_kirby_pupupu64": "Dream Land",
    "ui_stage_poke_yamabuki": "Saffron City",
    "ui_stage_mario_past64": "Mushroom Kingdom",
    "ui_stage_mario_castledx": "Princess Peach's Castle",
    "ui_stage_mario_rainbow": "Rainbow Cruise",
    "ui_stage_dk_waterfall": "Kongo Falls",
    "ui_stage_dk_lodge": "Jungle Japes",
    "ui_stage_zelda_greatbay": "Great Bay",
    "ui_stage_zelda_temple": "Temple",
    "ui_stage_metroid_zebesdx": "Brinstar",
    "ui_stage_yoshi_yoster": "Yoshi's Island (Melee)",
    "ui_stage_yoshi_cartboard": "Yoshi's Story",
    "ui_stage_kirby_fountain": "Fountain of Dreams",
    "ui_stage_kirby_greens": "Greens Greens",
    "ui_stage_fox_corneria": "Corneria",
    "ui_stage_fox_venom": "Venom",
    "ui_stage_poke_stadium": "Pokemon Stadium",
    "ui_stage_mother_onett": "Onett",
    "ui_stage_mario_pastusa": "Mushroom Kingdom II",
    "ui_stage_metroid_kraid": "Brinstar Depths",
    "ui_stage_fzero_bigblue": "Big Blue",
    "ui_stage_mother_fourside": "Fourside",
    "ui_stage_mario_dolpic": "Delfino Plaza",
    "ui_stage_mario_pastx": "Mushroomy Kingdom",
    "ui_stage_kart_circuitx": "Figure-8 Circuit",
    "ui_stage_wario_madein": "WarioWare, Inc.",
    "ui_stage_zelda_oldin": "Bridge of Eldin",
    "ui_stage_metroid_norfair": "Norfair",
    "ui_stage_metroid_orpheon": "Frigate Orpheon",
    "ui_stage_yoshi_island": "Yoshi's Island",
    "ui_stage_kirby_halberd": "Halberd",
    "ui_stage_fox_lylatcruise": "Lylat Cruise",
    "ui_stage_poke_stadium2": "Pokemon Stadium 2",
    "ui_stage_fzero_porttown": "Port Town Aero Dive",
    "ui_stage_fe_siege": "Castle Siege",
    "ui_stage_pikmin_planet": "Distant Planet",
    "ui_stage_animal_village": "Smashville",
    "ui_stage_mother_newpork": "New Pork City",
    "ui_stage_ice_top": "Summit",
    "ui_stage_icarus_skyworld": "Skyworld",
    "ui_stage_mg_shadowmoses": "Shadow Moses Island",
    "ui_stage_luigimansion": "Luigi's Mansion",
    "ui_stage_zelda_pirates": "Pirate Ship",
    "ui_stage_poke_tengam": "Spear Pillar",
    "ui_stage_75m": "75 m",
    "ui_stage_mariobros": "Mario Bros.",
    "ui_stage_plankton": "Hanenbow",
    "ui_stage_sonic_greenhill": "Green Hill Zone",
    "ui_stage_mario_3dland": "3D Land",
    "ui_stage_mario_newbros2": "Golden Plains",
    "ui_stage_mario_paper": "Paper Mario",
    "ui_stage_zelda_gerudo": "Gerudo Valley",
    "ui_stage_zelda_train": "Spirit Train",
    "ui_stage_kirby_gameboy": "Dream Land GB",
    "ui_stage_poke_unova": "Unova Pokemon League",
    "ui_stage_poke_tower": "Prism Tower",
    "ui_stage_fzero_mutecity3ds": "Mute City SNES",
    "ui_stage_mother_magicant": "Magicant",
    "ui_stage_fe_arena": "Arena Ferox",
    "ui_stage_icarus_uprising": "Reset Bomb Forest",
    "ui_stage_animal_island": "Tortimer Island",
    "ui_stage_balloonfight": "Balloon Fight",
    "ui_stage_nintendogs": "Living Room",
    "ui_stage_streetpass": "Find Mii",
    "ui_stage_tomodachi": "Tomodachi Life",
    "ui_stage_pictochat2": "PictoChat 2",
    "ui_stage_mario_uworld": "Mushroom Kingdom U",
    "ui_stage_mario_galaxy": "Mario Galaxy",
    "ui_stage_kart_circuitfor": "Mario Circuit",
    "ui_stage_zelda_skyward": "Skyloft",
    "ui_stage_kirby_cave": "The Great Cave Offensive",
    "ui_stage_poke_kalos": "Kalos Pokemon League",
    "ui_stage_fe_colloseum": "Coliseum",
    "ui_stage_flatzonex": "Flat Zone X",
    "ui_stage_icarus_angeland": "Palutena's Temple",
    "ui_stage_wario_gamer": "Gamer",
    "ui_stage_pikmin_garden": "Garden of Hope",
    "ui_stage_animal_city": "Town and City",
    "ui_stage_wiifit": "Wii Fit Studio",
    "ui_stage_punchoutsb": "Boxing Ring",
    "ui_stage_xeno_gaur": "Gaur Plain",
    "ui_stage_duckhunt": "Duck Hunt",
    "ui_stage_wreckingcrew": "Wrecking Crew",
    "ui_stage_pilotwings": "Pilotwings",
    "ui_stage_wufuisland": "Wuhu Island",
    "ui_stage_sonic_windyhill": "Windy Hill Zone",
    "ui_stage_rock_wily": "Wily Castle",
    "ui_stage_pac_land": "PAC-LAND",
    "ui_stage_mario_maker": "Super Mario Maker",
    "ui_stage_sf_suzaku": "Suzaku Castle",
    "ui_stage_ff_midgar": "Midgar",
    "ui_stage_bayo_clock": "Umbra Clock Tower",
    "ui_stage_mario_odyssey": "New Donk City Hall",
    "ui_stage_zelda_tower": "Great Plateau Tower",
    "ui_stage_spla_parking": "Moray Towers",
    "ui_stage_dracula_castle": "Dracula's Castle",
    "ui_stage_training": "Training",
    "ui_stage_edit": "Custom Stage",
    "ui_stage_homerun": "Home-Run Stadium",
    "ui_stage_jack_mementoes": "Mementos",
    "ui_stage_brave_altar": "Yggdrasil's Altar",
    "ui_stage_buddy_spiral": "Spiral Mountain",
    "ui_stage_dolly_stadium": "King of Fighters Stadium",
    "ui_stage_fe_shrine": "Garreg Mach Monastery",
    "ui_stage_tantan_spring": "Spring Stadium",
    "ui_stage_pickel_world": "Minecraft World",
    "ui_stage_ff_cave": "Northern Cave",
    "ui_stage_xeno_alst": "Cloud Sea of Alrest",
    "ui_stage_demon_dojo": "Mishima Dojo",
    "ui_stage_trail_castle": "Hollow Bastion",
    "ui_stage_battle_field_s": "Small Battlefield",
}

# Older app builds saved assignments under placeholder `ui_stage_id_*` names.
# Keep accepting those keys so existing configs migrate transparently.
LEGACY_STAGE_ID_ALIASES = {
    "ui_stage_id_animal_city": "ui_stage_animal_city",
    "ui_stage_id_animal_island": "ui_stage_animal_island",
    "ui_stage_id_animal_village": "ui_stage_animal_village",
    "ui_stage_id_balloonfight": "ui_stage_balloonfight",
    "ui_stage_id_battle_skyworld": "ui_stage_icarus_skyworld",
    "ui_stage_id_battlefield": "ui_stage_battle_field",
    "ui_stage_id_battlefield_l": "ui_stage_battle_field_l",
    "ui_stage_id_battlefield_s": "ui_stage_battle_field_s",
    "ui_stage_id_bayo_clock": "ui_stage_bayo_clock",
    "ui_stage_id_brave_altar": "ui_stage_brave_altar",
    "ui_stage_id_demon_dojo": "ui_stage_demon_dojo",
    "ui_stage_id_dk_jungle": "ui_stage_dk_jungle",
    "ui_stage_id_dk_lodge": "ui_stage_dk_lodge",
    "ui_stage_id_dk_returns": "ui_stage_dk_lodge",
    "ui_stage_id_dk_waterfall": "ui_stage_dk_waterfall",
    "ui_stage_id_dolly_stadium": "ui_stage_dolly_stadium",
    "ui_stage_id_dracula_castle": "ui_stage_dracula_castle",
    "ui_stage_id_duckhunt_village": "ui_stage_duckhunt",
    "ui_stage_id_electroplankton": "ui_stage_plankton",
    "ui_stage_id_end": "ui_stage_end",
    "ui_stage_id_fe_arena": "ui_stage_fe_arena",
    "ui_stage_id_fe_colosseum": "ui_stage_fe_colloseum",
    "ui_stage_id_fe_siege": "ui_stage_fe_siege",
    "ui_stage_id_ff_midgar": "ui_stage_ff_midgar",
    "ui_stage_id_flatzone_x": "ui_stage_flatzonex",
    "ui_stage_id_fw_shrine": "ui_stage_pikmin_garden",
    "ui_stage_id_fzero_bigblue": "ui_stage_fzero_bigblue",
    "ui_stage_id_fzero_mutecity3ds": "ui_stage_fzero_mutecity3ds",
    "ui_stage_id_fzero_porttown": "ui_stage_fzero_porttown",
    "ui_stage_id_homerun_stadium": "ui_stage_homerun",
    "ui_stage_id_iceclimber_summit": "ui_stage_ice_top",
    "ui_stage_id_jack_mementoes": "ui_stage_jack_mementoes",
    "ui_stage_id_kaclash_castle": "ui_stage_streetpass",
    "ui_stage_id_kirby_fountain": "ui_stage_kirby_fountain",
    "ui_stage_id_kirby_gameboy": "ui_stage_kirby_gameboy",
    "ui_stage_id_kirby_halberd": "ui_stage_kirby_halberd",
    "ui_stage_id_kirby_pupupu64": "ui_stage_kirby_pupupu64",
    "ui_stage_id_lylat_corneria": "ui_stage_fox_corneria",
    "ui_stage_id_lylat_sector": "ui_stage_fox_lylatcruise",
    "ui_stage_id_lylat_venom": "ui_stage_fox_venom",
    "ui_stage_id_mario_3dland": "ui_stage_mario_3dland",
    "ui_stage_id_mario_castle64": "ui_stage_mario_castle64",
    "ui_stage_id_mario_dolpic": "ui_stage_mario_dolpic",
    "ui_stage_id_mario_maker": "ui_stage_mario_maker",
    "ui_stage_id_mario_newndonk": "ui_stage_mario_odyssey",
    "ui_stage_id_mario_odyssey": "ui_stage_mario_odyssey",
    "ui_stage_id_mario_paper": "ui_stage_mario_paper",
    "ui_stage_id_mario_past64": "ui_stage_mario_past64",
    "ui_stage_id_mario_pastusa": "ui_stage_mario_pastusa",
    "ui_stage_id_mario_pastx": "ui_stage_mario_pastx",
    "ui_stage_id_mario_rainbow": "ui_stage_mario_rainbow",
    "ui_stage_id_mario_uworld": "ui_stage_mario_uworld",
    "ui_stage_id_metroid_brinstar": "ui_stage_metroid_zebesdx",
    "ui_stage_id_metroid_kraid": "ui_stage_metroid_kraid",
    "ui_stage_id_metroid_norfair": "ui_stage_metroid_norfair",
    "ui_stage_id_metroid_orpheon": "ui_stage_metroid_orpheon",
    "ui_stage_id_mg_shadowmoses": "ui_stage_mg_shadowmoses",
    "ui_stage_id_minecraft_world": "ui_stage_pickel_world",
    "ui_stage_id_mother_magicant": "ui_stage_mother_magicant",
    "ui_stage_id_mother_newpork": "ui_stage_mother_newpork",
    "ui_stage_id_mother_onett": "ui_stage_mother_onett",
    "ui_stage_id_nintendogs": "ui_stage_nintendogs",
    "ui_stage_id_pac_land": "ui_stage_pac_land",
    "ui_stage_id_pictochat2": "ui_stage_pictochat2",
    "ui_stage_id_pikmin_planet": "ui_stage_pikmin_planet",
    "ui_stage_id_pilotwings": "ui_stage_pilotwings",
    "ui_stage_id_poke_kalos": "ui_stage_poke_kalos",
    "ui_stage_id_poke_stadium": "ui_stage_poke_stadium",
    "ui_stage_id_poke_stadium2": "ui_stage_poke_stadium2",
    "ui_stage_id_poke_tengam": "ui_stage_poke_tengam",
    "ui_stage_id_poke_unova": "ui_stage_poke_unova",
    "ui_stage_id_poke_yamabuki": "ui_stage_poke_yamabuki",
    "ui_stage_id_punchoutsb": "ui_stage_punchoutsb",
    "ui_stage_id_sf_suzaku": "ui_stage_sf_suzaku",
    "ui_stage_id_sonic_greenhill": "ui_stage_sonic_greenhill",
    "ui_stage_id_sonic_windyhill": "ui_stage_sonic_windyhill",
    "ui_stage_id_sp_edit": "ui_stage_edit",
    "ui_stage_id_splatoon_stage": "ui_stage_spla_parking",
    "ui_stage_id_stranger_dungeon": "ui_stage_trail_castle",
    "ui_stage_id_tantan_spring": "ui_stage_tantan_spring",
    "ui_stage_id_tomodachi": "ui_stage_tomodachi",
    "ui_stage_id_trail_castle": "ui_stage_trail_castle",
    "ui_stage_id_training": "ui_stage_training",
    "ui_stage_id_wario_gamer": "ui_stage_wario_gamer",
    "ui_stage_id_wario_madein": "ui_stage_wario_madein",
    "ui_stage_id_wiifit_gym": "ui_stage_wiifit",
    "ui_stage_id_wreckingcrew": "ui_stage_wreckingcrew",
    "ui_stage_id_wuhu_island": "ui_stage_wufuisland",
    "ui_stage_id_xeno_alst": "ui_stage_xeno_alst",
    "ui_stage_id_xeno_gaur": "ui_stage_xeno_gaur",
    "ui_stage_id_yoshi_cartboard": "ui_stage_yoshi_cartboard",
    "ui_stage_id_yoshi_story": "ui_stage_yoshi_story",
    "ui_stage_id_yoshi_yoster": "ui_stage_yoshi_yoster",
    "ui_stage_id_zelda_gerudo": "ui_stage_zelda_gerudo",
    "ui_stage_id_zelda_greatbay": "ui_stage_zelda_greatbay",
    "ui_stage_id_zelda_hyrule": "ui_stage_zelda_hyrule",
    "ui_stage_id_zelda_oldin": "ui_stage_zelda_oldin",
    "ui_stage_id_zelda_skyward": "ui_stage_zelda_skyward",
    "ui_stage_id_zelda_temple": "ui_stage_zelda_temple",
    "ui_stage_id_zelda_tower": "ui_stage_zelda_tower",
}

# File types that can cause conflicts
CONFLICT_EXTENSIONS = {".xmsbt", ".msbt", ".prc", ".stprm", ".stdat"}
MERGEABLE_EXTENSIONS = {".xmsbt"}

# Tournament-legal competitive stages (commonly used in official rulesets)
COMPETITIVE_STAGES = {
    "ui_stage_battle_field",
    "ui_stage_battle_field_s",
    "ui_stage_end",
    "ui_stage_animal_village",   # Smashville
    "ui_stage_animal_city",      # Town and City
    "ui_stage_poke_stadium2",    # Pokemon Stadium 2
    "ui_stage_poke_kalos",       # Kalos Pokemon League
    "ui_stage_trail_castle",     # Hollow Bastion
    "ui_stage_ff_cave",          # Northern Cave
    "ui_stage_yoshi_story",      # Super Happy Tree (Yoshi's Story)
}

# File categories based on path patterns
FILE_CATEGORIES = {
    "character": ["fighter/", "ui/replace/chara/", "sound/bank/narration/"],
    "music": ["sound/bgm/", "stream/"],
    "stage": ["stage/", "ui/replace/stage/"],
    "ui": ["ui/", "param/"],
    "effect": ["effect/"],
}

SIDEBAR_WIDTH = 200
